micronaut:
  application:
    name: micronautguide1
  server:
    context-path: /demo
    port: 8090
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  caches:
    api-key:
      expire-after-write: 10s
netty:
  default:
    allocator:
      max-order: 3

greeting:
  message: Hello from micronaut guide default env
  environmentVariable: ${TEST_ENV_VAR}

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123

flyway:
  datasources:
    default:
      #If you need more control to decide when the migrations are executed it is possible to configure the
      #application like this
      #enabled: false
      enabled: true
      locations: classpath:db/migration