CREATE TABLE IF NOT EXISTS book (
   id BIGINT NOT NULL UNIQUE PRIMARY KEY,
   name VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE IF EXISTS public.book ADD CONSTRAINT name_unique UNIQUE (name);
ALTER TABLE IF EXISTS public.book ADD CONSTRAINT id_unique UNIQUE (id);
ALTER TABLE IF EXISTS public.book ALTER COLUMN name SET NOT NULL;